In [43]:
import numpy as np
array1= np.array([[1,1],[2,2]])
print(array1)

[[1 1]
 [2 2]]


In [ ]:
array2random=np.random.rand(3,4)
print(array2random)

[[0.98340765 0.85418557 0.14409006 0.55379407]
 [0.96527042 0.28617728 0.69992298 0.64671477]
 [0.14892546 0.82341029 0.43328997 0.17303272]]


In [ ]:
array3=np.ones((3,3))
array4=np.zeros((3,3))
print("Array ones:\n", array3)
print("Array zeros:\n", array4)

Array ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array5= np.random.rand(6,3)
print("Original array:\n", array5)
transpose_array5=array5.T
print("Transpose array:\n", transpose_array5)

Original array:
 [[0.67185067 0.03342234 0.73679221]
 [0.47637195 0.88544214 0.15651155]
 [0.18283319 0.15411996 0.57971757]
 [0.77794597 0.65226216 0.79281543]
 [0.70214402 0.30334557 0.92010993]
 [0.85517066 0.54260319 0.24160678]]
Transpose array:
 [[0.67185067 0.47637195 0.18283319 0.77794597 0.70214402 0.85517066]
 [0.03342234 0.88544214 0.15411996 0.65226216 0.30334557 0.54260319]
 [0.73679221 0.15651155 0.57971757 0.79281543 0.92010993 0.24160678]]


In [ ]:
n=np.random.randint(2,8)
p=np.random.randint(2,8)
m=np.random.randint(2,8)

array_1=np.random.rand(n,p)
array_2=np.random.rand(p,m)

print("Matrix A:\n", array_1)
print("Matrix B:\n", array_2)

dot_product=np.dot(array_1,array_2)
print("\n Dot product:\n",dot_product)

Matrix A:
 [[0.23781224 0.14714119 0.71733669 0.17554906 0.09542026 0.42373393
  0.56017961]
 [0.77375217 0.56940262 0.40487971 0.15754347 0.21999545 0.12960196
  0.5829858 ]
 [0.197878   0.32190518 0.45525269 0.57599933 0.78397899 0.96062258
  0.38145773]]
Matrix B:
 [[0.87096584 0.71458342 0.88507192]
 [0.39789421 0.13729659 0.84137345]
 [0.4441636  0.94368845 0.36567866]
 [0.35651152 0.25980444 0.92902184]
 [0.29831766 0.15995197 0.31639897]
 [0.94501518 0.46793677 0.04773192]
 [0.29906711 0.26291896 0.78204993]]

 Dot product:
 [[1.24330492 1.27351463 1.24819019]
 [1.49892884 1.30321056 1.99004025]
 [1.96374541 1.44006279 1.73979239]]


In [45]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [46]:
%cd /content/drive/MyDrive/Colab Notebooks/

/content/drive/MyDrive/Colab Notebooks


In [47]:
%cd /content/drive/MyDrive/git_repos/data-science-VLYS

/content/drive/MyDrive/git_repos/data-science-VLYS


In [48]:
!git config --global user.email "25005653@siswa.um.edu.my"
!git config --global user.name "VincentLohYongSheng-2025"

In [58]:
!git add "NumpyTutorial1.ipynb"
!git commit -m "Numpy tutorial (Week 3)"
!git push https://VincentLohYongSheng-2025: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@github.com/VincentLohYongSheng-2025/data-science-VLYS.git main


[main 1e88064] Numpy tutorial (Week 3)
 1 file changed, 1 insertion(+), 1 deletion(-)
To https://github.com/VincentLohYongSheng-2025/data-science-VLYS.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/VincentLohYongSheng-2025/data-science-VLYS.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
